#!/bin/sh
# Hyperworkflows universal adapter installer.
# Usage: sh adapters/install.sh <tool> <target-project-dir>
#        sh adapters/install.sh all <target-project-dir>
#
# Tools: agents-md codex amp jules cursor copilot gemini windsurf opencode
#        cline roo aider qwen kiro warp zed junie trae devin
#
# Every install first lays down the portable core at <target>/.hyperworkflows/
# (adjudicate.mjs, recheck.mjs, rules.md, role-prompts.md), then writes the
# tool-native pointer files (rules) and commands where the tool supports them.
# Marked sections (<!-- HYPERWORKFLOWS-BEGIN --> ... <!-- HYPERWORKFLOWS-END -->) are replaced on
# re-install, so running twice never duplicates content.

set -e

TOOL="$1"
TARGET="$2"
[ -n "$TOOL" ] && [ -n "$TARGET" ] || { echo "usage: install.sh <tool|all> <target-project-dir>" >&2; exit 2; }
[ -d "$TARGET" ] || { echo "target does not exist: $TARGET" >&2; exit 2; }

HERE=$(cd "$(dirname "$0")" && pwd)
ROOT=$(cd "$HERE/.." && pwd)
CORE="$HERE/core"
BEGIN="<!-- HYPERWORKFLOWS-BEGIN (generated by hyperworkflows adapters/install.sh; re-run to update) -->"
END="<!-- HYPERWORKFLOWS-END -->"

# ---------------------------------------------------------------- core ------
install_core() {
  mkdir -p "$TARGET/.hyperworkflows"
  cp "$ROOT/scripts/adjudicate.mjs" "$TARGET/.hyperworkflows/adjudicate.mjs"
  cp "$ROOT/scripts/recheck.mjs" "$TARGET/.hyperworkflows/recheck.mjs"
  cp "$CORE/rules.md" "$TARGET/.hyperworkflows/rules.md"
  OUT="$TARGET/.hyperworkflows/role-prompts.md"
  {
    echo "# Hyperworkflows role contracts (generated from agents/*.md — regenerate with adapters/install.sh)"
    echo
    for f in "$ROOT"/agents/hyperworkflows-*.md; do
      echo "## $(basename "$f" .md)"
      echo
      awk 'BEGIN{fm=0} /^---$/{fm++; next} fm>=2{print}' "$f"
      echo
    done
  } > "$OUT"
  echo "core: .hyperworkflows/ (adjudicate.mjs, recheck.mjs, rules.md, role-prompts.md)"
}

# Short pointer text used by every rules surface.
stub() {
  cat <<'EOF'
# Hyperworkflows (Hyperworkflows) evidence discipline

This project uses Hyperworkflows. Follow `.hyperworkflows/rules.md` STRICTLY:

- Verdicts are computed by script, never by the model: `node .hyperworkflows/adjudicate.mjs adjudicate '<json>'`.
- Every unit of work needs executable acceptance `{cmd, expect_exit}`; missing oracles are forged first (see hyperworkflows-rules).
- Findings need executed repros; verification runs in a fresh context with commands only.
- Every deliverable is a tricolor report (VERIFIED / DONE-UNVERIFIED / QUARANTINED+GREY) with coverage arithmetic and verdict files under `runs/`.
- Any report can be re-verified with zero LLM calls: `node .hyperworkflows/recheck.mjs runs/<run-id>`.
- Role contracts for delegation: `.hyperworkflows/role-prompts.md`.
EOF
}

# append_marked <file>  (content on stdin) — replace existing Hyperworkflows block or append.
append_marked() {
  file="$1"
  mkdir -p "$(dirname "$file")"
  tmp_content=$(mktemp) && cat > "$tmp_content"
  if [ -f "$file" ] && grep -qF "$BEGIN" "$file"; then
    tmp_out=$(mktemp)
    awk -v b="$BEGIN" -v e="$END" -v cf="$tmp_content" '
      $0 == b { print; while ((getline line < cf) > 0) print line; close(cf); skip = 1; next }
      $0 == e { print; skip = 0; next }
      !skip { print }
    ' "$file" > "$tmp_out"
    mv "$tmp_out" "$file"
  else
    { [ -f "$file" ] && [ -s "$file" ] && echo; echo "$BEGIN"; cat "$tmp_content"; echo "$END"; } >> "$file"
  fi
  rm -f "$tmp_content"
  echo "rules: $file"
}

# write_cmd <path> <frontmatter-or-empty> <core-command-file>
write_cmd() {
  mkdir -p "$(dirname "$1")"
  { [ -n "$2" ] && printf '%s\n' "$2"; cat "$CORE/commands/$3"; } > "$1"
  echo "command: $1"
}

# write_toml_cmd <path> <description> <core-command-file>
write_toml_cmd() {
  mkdir -p "$(dirname "$1")"
  { printf 'description = "%s"\nprompt = """\n' "$2"; cat "$CORE/commands/$3"; printf '"""\n'; } > "$1"
  echo "command: $1"
}

# ---------------------------------------------------------------- tools -----
do_agents_md() { stub | append_marked "$TARGET/AGENTS.md"; }

do_cursor() {
  mkdir -p "$TARGET/.cursor/rules"
  { printf -- '---\ndescription: Hyperworkflows evidence discipline (Hyperworkflows)\nalwaysApply: true\n---\n\n'; stub; } > "$TARGET/.cursor/rules/hyperworkflows.mdc"
  echo "rules: $TARGET/.cursor/rules/hyperworkflows.mdc"
  write_cmd "$TARGET/.cursor/commands/hyperworkflows-audit.md" "" audit.md
  write_cmd "$TARGET/.cursor/commands/hyperworkflows-apply.md" "" apply.md
  write_cmd "$TARGET/.cursor/commands/hyperworkflows-recheck.md" "" recheck.md
}

do_copilot() {
  stub | append_marked "$TARGET/.github/copilot-instructions.md"
  mkdir -p "$TARGET/.github/instructions"
  { printf -- '---\napplyTo: "**"\n---\n\n'; stub; } > "$TARGET/.github/instructions/hyperworkflows.instructions.md"
  echo "rules: $TARGET/.github/instructions/hyperworkflows.instructions.md"
}

do_gemini() {
  stub | append_marked "$TARGET/GEMINI.md"
  write_toml_cmd "$TARGET/.gemini/commands/hyperworkflows/audit.toml" "Hyperworkflows evidence-grade audit with script-computed verdicts" audit.md
  write_toml_cmd "$TARGET/.gemini/commands/hyperworkflows/apply.toml" "Hyperworkflows disciplined delivery with gated full-suite verification" apply.md
  write_toml_cmd "$TARGET/.gemini/commands/hyperworkflows/recheck.toml" "Re-verify an Hyperworkflows report with zero LLM calls" recheck.md
}

do_windsurf() {
  mkdir -p "$TARGET/.windsurf/rules"
  stub > "$TARGET/.windsurf/rules/hyperworkflows.md"
  echo "rules: $TARGET/.windsurf/rules/hyperworkflows.md"
  write_cmd "$TARGET/.windsurf/workflows/hyperworkflows-audit.md" "---
description: Hyperworkflows evidence-grade audit with script-computed verdicts
---" audit.md
  write_cmd "$TARGET/.windsurf/workflows/hyperworkflows-apply.md" "---
description: Hyperworkflows disciplined delivery with gated full-suite verification
---" apply.md
  write_cmd "$TARGET/.windsurf/workflows/hyperworkflows-recheck.md" "---
description: Re-verify an Hyperworkflows report with zero LLM calls
---" recheck.md
}

do_opencode() {
  do_agents_md
  write_cmd "$TARGET/.opencode/command/hyperworkflows-audit.md" "---
description: Hyperworkflows evidence-grade audit with script-computed verdicts
---" audit.md
  write_cmd "$TARGET/.opencode/command/hyperworkflows-apply.md" "---
description: Hyperworkflows disciplined delivery with gated full-suite verification
---" apply.md
  write_cmd "$TARGET/.opencode/command/hyperworkflows-recheck.md" "---
description: Re-verify an Hyperworkflows report with zero LLM calls
---" recheck.md
}

do_cline()  { mkdir -p "$TARGET/.clinerules"; stub > "$TARGET/.clinerules/hyperworkflows.md"; echo "rules: $TARGET/.clinerules/hyperworkflows.md"; }
do_roo()    { mkdir -p "$TARGET/.roo/rules"; stub > "$TARGET/.roo/rules/hyperworkflows.md"; echo "rules: $TARGET/.roo/rules/hyperworkflows.md"; }
do_aider()  { stub | append_marked "$TARGET/CONVENTIONS.md"; echo "note: ensure .aider.conf.yml contains: read: [CONVENTIONS.md]"; }
do_qwen()   { stub | append_marked "$TARGET/QWEN.md"; }
do_warp()   { stub | append_marked "$TARGET/WARP.md"; }
do_zed()    { stub | append_marked "$TARGET/.rules"; }
do_junie()  { stub | append_marked "$TARGET/.junie/guidelines.md"; }
do_trae()   { mkdir -p "$TARGET/.trae/rules"; stub > "$TARGET/.trae/rules/hyperworkflows.md"; echo "rules: $TARGET/.trae/rules/hyperworkflows.md"; }
do_kiro() {
  mkdir -p "$TARGET/.kiro/steering"
  { printf -- '---\ninclusion: always\n---\n\n'; stub; } > "$TARGET/.kiro/steering/hyperworkflows.md"
  echo "rules: $TARGET/.kiro/steering/hyperworkflows.md"
}
do_devin()  { sh "$HERE/devin/install.sh" "$TARGET"; }

run_tool() {
  case "$1" in
    agents-md|codex|amp|jules) do_agents_md ;;
    cursor)    do_cursor ;;
    copilot)   do_copilot ;;
    gemini)    do_gemini ;;
    windsurf)  do_windsurf ;;
    opencode)  do_opencode ;;
    cline)     do_cline ;;
    roo)       do_roo ;;
    aider)     do_aider ;;
    qwen)      do_qwen ;;
    kiro)      do_kiro ;;
    warp)      do_warp ;;
    zed)       do_zed ;;
    junie)     do_junie ;;
    trae)      do_trae ;;
    devin)     do_devin ;;
    *) echo "unknown tool: $1" >&2; exit 2 ;;
  esac
}

install_core
if [ "$TOOL" = "all" ]; then
  for t in agents-md cursor copilot gemini windsurf opencode cline roo aider qwen kiro warp zed junie trae devin; do
    echo "--- $t"
    run_tool "$t"
  done
else
  run_tool "$TOOL"
fi
echo "done."
